/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.utilerias;

import javax.swing.BoxLayout;

/**
 *
 * @author cinca
 */
public class pnlResumenPedido extends javax.swing.JPanel {

    /**
     * Creates new form pnlResumenPedido
     */
    public pnlResumenPedido() {
        initComponents();
        
        pnlContenedprProd.setLayout(new BoxLayout(pnlContenedprProd, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContenedprProd = new javax.swing.JPanel();
        pnlImgProducto = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblNombreProducto = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        pnlTotales = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        lblTituloSubtotal = new javax.swing.JLabel();
        lblTituloTax = new javax.swing.JLabel();
        lblTituloTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSubtotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarCarrito = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(348, 640));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resumen");

        pnlContenedprProd.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlImgProductoLayout = new javax.swing.GroupLayout(pnlImgProducto);
        pnlImgProducto.setLayout(pnlImgProductoLayout);
        pnlImgProductoLayout.setHorizontalGroup(
            pnlImgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        pnlImgProductoLayout.setVerticalGroup(
            pnlImgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        lblNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreProducto.setText("Nombre producto");

        lblArtista.setForeground(new java.awt.Color(102, 102, 102));
        lblArtista.setText("Artista");

        jLabel4.setText("Precio");

        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("$0");

        javax.swing.GroupLayout pnlContenedprProdLayout = new javax.swing.GroupLayout(pnlContenedprProd);
        pnlContenedprProd.setLayout(pnlContenedprProdLayout);
        pnlContenedprProdLayout.setHorizontalGroup(
            pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedprProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedprProdLayout.createSequentialGroup()
                        .addComponent(lblNombreProducto)
                        .addGap(78, 78, 78)
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(lblArtista))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlContenedprProdLayout.setVerticalGroup(
            pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedprProdLayout.createSequentialGroup()
                .addGroup(pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedprProdLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnlImgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedprProdLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlContenedprProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreProducto)
                            .addComponent(jLabel4)
                            .addComponent(lblPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArtista)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlContenedprProd);

        pnlTotales.setBackground(new java.awt.Color(153, 153, 153));
        pnlTotales.setForeground(new java.awt.Color(153, 153, 153));

        btnContinuar.setBackground(new java.awt.Color(204, 0, 0));
        btnContinuar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnContinuar.setText("Continuar");

        lblTituloSubtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloSubtotal.setText("Subtotal:");

        lblTituloTax.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloTax.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloTax.setText("Tax (16%):");

        lblTituloTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloTotal.setText("Total:");

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lblSubtotal.setText("$0");

        lblTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTax.setForeground(new java.awt.Color(51, 51, 51));
        lblTax.setText("$0");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("$0");

        javax.swing.GroupLayout pnlTotalesLayout = new javax.swing.GroupLayout(pnlTotales);
        pnlTotales.setLayout(pnlTotalesLayout);
        pnlTotalesLayout.setHorizontalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTituloSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubtotal))
                    .addGroup(pnlTotalesLayout.createSequentialGroup()
                        .addComponent(lblTituloTax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTax)))
                .addGap(29, 29, 29))
            .addGroup(pnlTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addGap(28, 28, 28))
        );
        pnlTotalesLayout.setVerticalGroup(
            pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalesLayout.createSequentialGroup()
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloSubtotal)
                    .addComponent(lblSubtotal))
                .addGap(18, 18, 18)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloTax)
                    .addComponent(lblTax))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloTotal)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\cinca\\Documents\\carro 1.png")); // NOI18N

        btnEliminarCarrito.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarCarrito.setForeground(new java.awt.Color(204, 0, 0));
        btnEliminarCarrito.setText("Eliminar carrito");
        btnEliminarCarrito.setBorder(null);
        btnEliminarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarCarrito)
                .addGap(21, 21, 21))
            .addComponent(pnlTotales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(btnEliminarCarrito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEliminarCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTituloSubtotal;
    private javax.swing.JLabel lblTituloTax;
    private javax.swing.JLabel lblTituloTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlContenedprProd;
    private javax.swing.JPanel pnlImgProducto;
    private javax.swing.JPanel pnlTotales;
    // End of variables declaration//GEN-END:variables
}
