package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.utilerias.pnlBarraSuperior;
import itson.rog.ghosttracks.controladores.ControlVentaEnLinea;

/**
 *
 * @author emyla
 */
public class VistaProducto extends javax.swing.JFrame {
    
    private ControlVentaEnLinea control;
    private pnlBarraSuperior barraSuperior;
    /**
     * Creates new form VistaProducto
     */
    public VistaProducto(ControlVentaEnLinea control) {
        this.control = control;
        initComponents();
        barraSuperior = new pnlBarraSuperior();
        pnlBase.add(barraSuperior);
        pnlBase.revalidate();
        pnlBase.repaint();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFondo = new javax.swing.JPanel();
        pnlBase = new itson.org.ghosttracks.utilerias.pnlBarraSuperior();
        panelRedondeado1 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        panelRedondeado4 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlDatosProducto = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblNombreProducto = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        panelRedondeado2 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblCantidad = new javax.swing.JLabel();
        pnlMenos = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel1 = new javax.swing.JLabel();
        pnlMas = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel2 = new javax.swing.JLabel();
        lblUnidad = new javax.swing.JLabel();
        btnAniadirAlCarrito = new javax.swing.JButton();
        lblSetlist = new javax.swing.JLabel();
        panelRedondeado3 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblNombreProducto1 = new javax.swing.JLabel();
        pnlSugerencia01 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgSug01 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblProductSug01 = new javax.swing.JLabel();
        lblArtistSug01 = new javax.swing.JLabel();
        lblPrecioSug01 = new javax.swing.JLabel();
        pnlSugerencia02 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgSug02 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblProductSug02 = new javax.swing.JLabel();
        lblArtistSug02 = new javax.swing.JLabel();
        lblPrecioSug02 = new javax.swing.JLabel();
        pnlSugerencia03 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgSug03 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblProductSug03 = new javax.swing.JLabel();
        lblArtistSug03 = new javax.swing.JLabel();
        lblPrecioSug03 = new javax.swing.JLabel();
        pnlSugerencia04 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgSug04 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblProductSug04 = new javax.swing.JLabel();
        lblArtistSug04 = new javax.swing.JLabel();
        lblPrecioSug04 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlFondo.setBackground(new java.awt.Color(237, 229, 222));

        pnlBase.setMinimumSize(new java.awt.Dimension(1413, 100));
        pnlBase.setLayout(new java.awt.BorderLayout());

        panelRedondeado1.setBackground(new java.awt.Color(217, 217, 217));

        panelRedondeado4.setBackground(new java.awt.Color(230, 230, 230));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoFavoritos.png"))); // NOI18N

        javax.swing.GroupLayout panelRedondeado4Layout = new javax.swing.GroupLayout(panelRedondeado4);
        panelRedondeado4.setLayout(panelRedondeado4Layout);
        panelRedondeado4Layout.setHorizontalGroup(
            panelRedondeado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado4Layout.createSequentialGroup()
                .addContainerGap(618, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );
        panelRedondeado4Layout.setVerticalGroup(
            panelRedondeado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desplazarDerecha.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desplazarIzquierda.png"))); // NOI18N

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(518, 518, 518)
                        .addComponent(jLabel3))
                    .addComponent(panelRedondeado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelRedondeado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosProducto.setBackground(new java.awt.Color(217, 217, 217));

        lblNombreProducto.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("Nombre del producto");
        lblNombreProducto.setToolTipText("");

        lblArtista.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblArtista.setForeground(new java.awt.Color(102, 102, 102));
        lblArtista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArtista.setText("Artista");

        lblPrecio.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("$00.00");
        lblPrecio.setToolTipText("");

        lblCantidad.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("0");
        lblCantidad.setToolTipText("");

        javax.swing.GroupLayout panelRedondeado2Layout = new javax.swing.GroupLayout(panelRedondeado2);
        panelRedondeado2.setLayout(panelRedondeado2Layout);
        panelRedondeado2Layout.setHorizontalGroup(
            panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRedondeado2Layout.setVerticalGroup(
            panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMenos.setBackground(new java.awt.Color(196, 196, 196));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoRestar.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenosLayout = new javax.swing.GroupLayout(pnlMenos);
        pnlMenos.setLayout(pnlMenosLayout);
        pnlMenosLayout.setHorizontalGroup(
            pnlMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        pnlMenosLayout.setVerticalGroup(
            pnlMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMas.setBackground(new java.awt.Color(196, 196, 196));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoAgregar.png"))); // NOI18N

        javax.swing.GroupLayout pnlMasLayout = new javax.swing.GroupLayout(pnlMas);
        pnlMas.setLayout(pnlMasLayout);
        pnlMasLayout.setHorizontalGroup(
            pnlMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMasLayout.setVerticalGroup(
            pnlMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUnidad.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblUnidad.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidad.setText("pzas.");

        btnAniadirAlCarrito.setBackground(new java.awt.Color(255, 122, 37));
        btnAniadirAlCarrito.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAniadirAlCarrito.setForeground(new java.awt.Color(0, 0, 0));
        btnAniadirAlCarrito.setText("Añadir al carrito");
        btnAniadirAlCarrito.setPreferredSize(new java.awt.Dimension(200, 35));

        lblSetlist.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSetlist.setForeground(new java.awt.Color(102, 102, 102));
        lblSetlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetlist.setText("setlist");

        javax.swing.GroupLayout pnlDatosProductoLayout = new javax.swing.GroupLayout(pnlDatosProducto);
        pnlDatosProducto.setLayout(pnlDatosProductoLayout);
        pnlDatosProductoLayout.setHorizontalGroup(
            pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosProductoLayout.createSequentialGroup()
                .addGroup(pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosProductoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosProductoLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(pnlMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                        .addComponent(btnAniadirAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                        .addComponent(lblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                        .addGroup(pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSetlist, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        pnlDatosProductoLayout.setVerticalGroup(
            pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosProductoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblNombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblSetlist, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosProductoLayout.createSequentialGroup()
                        .addGroup(pnlDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProductoLayout.createSequentialGroup()
                        .addComponent(panelRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(lblUnidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAniadirAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panelRedondeado3.setBackground(new java.awt.Color(217, 217, 217));

        lblNombreProducto1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblNombreProducto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreProducto1.setText("Tambien podría gustarte...");
        lblNombreProducto1.setToolTipText("");

        pnlSugerencia01.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout pnlImgSug01Layout = new javax.swing.GroupLayout(pnlImgSug01);
        pnlImgSug01.setLayout(pnlImgSug01Layout);
        pnlImgSug01Layout.setHorizontalGroup(
            pnlImgSug01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgSug01Layout.setVerticalGroup(
            pnlImgSug01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        lblProductSug01.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblProductSug01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductSug01.setText("Producto Sugerido 01");

        lblArtistSug01.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArtistSug01.setForeground(new java.awt.Color(102, 102, 102));
        lblArtistSug01.setText("Artista 01");

        lblPrecioSug01.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblPrecioSug01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecioSug01.setText("$00.00");

        javax.swing.GroupLayout pnlSugerencia01Layout = new javax.swing.GroupLayout(pnlSugerencia01);
        pnlSugerencia01.setLayout(pnlSugerencia01Layout);
        pnlSugerencia01Layout.setHorizontalGroup(
            pnlSugerencia01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSugerencia01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImgSug01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProductSug01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioSug01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSugerencia01Layout.createSequentialGroup()
                        .addComponent(lblArtistSug01, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSugerencia01Layout.setVerticalGroup(
            pnlSugerencia01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgSug01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductSug01, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArtistSug01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioSug01, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSugerencia02.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout pnlImgSug02Layout = new javax.swing.GroupLayout(pnlImgSug02);
        pnlImgSug02.setLayout(pnlImgSug02Layout);
        pnlImgSug02Layout.setHorizontalGroup(
            pnlImgSug02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgSug02Layout.setVerticalGroup(
            pnlImgSug02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        lblProductSug02.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblProductSug02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductSug02.setText("Producto Sugerido 02");

        lblArtistSug02.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArtistSug02.setForeground(new java.awt.Color(102, 102, 102));
        lblArtistSug02.setText("Artista 02");

        lblPrecioSug02.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblPrecioSug02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecioSug02.setText("$00.00");

        javax.swing.GroupLayout pnlSugerencia02Layout = new javax.swing.GroupLayout(pnlSugerencia02);
        pnlSugerencia02.setLayout(pnlSugerencia02Layout);
        pnlSugerencia02Layout.setHorizontalGroup(
            pnlSugerencia02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSugerencia02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImgSug02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSugerencia02Layout.createSequentialGroup()
                        .addComponent(lblArtistSug02, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPrecioSug02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlSugerencia02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSugerencia02Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(lblProductSug02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        pnlSugerencia02Layout.setVerticalGroup(
            pnlSugerencia02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgSug02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblArtistSug02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioSug02, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(pnlSugerencia02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSugerencia02Layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(lblProductSug02)
                    .addContainerGap(73, Short.MAX_VALUE)))
        );

        pnlSugerencia03.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout pnlImgSug03Layout = new javax.swing.GroupLayout(pnlImgSug03);
        pnlImgSug03.setLayout(pnlImgSug03Layout);
        pnlImgSug03Layout.setHorizontalGroup(
            pnlImgSug03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgSug03Layout.setVerticalGroup(
            pnlImgSug03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        lblProductSug03.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblProductSug03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductSug03.setText("Producto Sugerido 03");

        lblArtistSug03.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArtistSug03.setForeground(new java.awt.Color(102, 102, 102));
        lblArtistSug03.setText("Artista 03");

        lblPrecioSug03.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblPrecioSug03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecioSug03.setText("$00.00");

        javax.swing.GroupLayout pnlSugerencia03Layout = new javax.swing.GroupLayout(pnlSugerencia03);
        pnlSugerencia03.setLayout(pnlSugerencia03Layout);
        pnlSugerencia03Layout.setHorizontalGroup(
            pnlSugerencia03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia03Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSugerencia03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImgSug03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSugerencia03Layout.createSequentialGroup()
                        .addComponent(lblArtistSug03, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(lblProductSug03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioSug03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSugerencia03Layout.setVerticalGroup(
            pnlSugerencia03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgSug03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductSug03, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblArtistSug03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecioSug03)
                .addContainerGap())
        );

        pnlSugerencia04.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout pnlImgSug04Layout = new javax.swing.GroupLayout(pnlImgSug04);
        pnlImgSug04.setLayout(pnlImgSug04Layout);
        pnlImgSug04Layout.setHorizontalGroup(
            pnlImgSug04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlImgSug04Layout.setVerticalGroup(
            pnlImgSug04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        lblProductSug04.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblProductSug04.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductSug04.setText("Producto Sugerido 04");

        lblArtistSug04.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArtistSug04.setForeground(new java.awt.Color(102, 102, 102));
        lblArtistSug04.setText("Artista 04");

        lblPrecioSug04.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblPrecioSug04.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecioSug04.setText("$00.00");

        javax.swing.GroupLayout pnlSugerencia04Layout = new javax.swing.GroupLayout(pnlSugerencia04);
        pnlSugerencia04.setLayout(pnlSugerencia04Layout);
        pnlSugerencia04Layout.setHorizontalGroup(
            pnlSugerencia04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia04Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSugerencia04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImgSug04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProductSug04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSugerencia04Layout.createSequentialGroup()
                        .addComponent(lblArtistSug04, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPrecioSug04, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSugerencia04Layout.setVerticalGroup(
            pnlSugerencia04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerencia04Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgSug04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductSug04, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArtistSug04)
                .addGap(18, 18, 18)
                .addComponent(lblPrecioSug04)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRedondeado3Layout = new javax.swing.GroupLayout(panelRedondeado3);
        panelRedondeado3.setLayout(panelRedondeado3Layout);
        panelRedondeado3Layout.setHorizontalGroup(
            panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRedondeado3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSugerencia03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSugerencia01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSugerencia02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSugerencia04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        panelRedondeado3Layout.setVerticalGroup(
            panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNombreProducto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSugerencia02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSugerencia01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSugerencia03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSugerencia04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRedondeado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRedondeado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlFondo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1425, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirAlCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtistSug01;
    private javax.swing.JLabel lblArtistSug02;
    private javax.swing.JLabel lblArtistSug03;
    private javax.swing.JLabel lblArtistSug04;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreProducto1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioSug01;
    private javax.swing.JLabel lblPrecioSug02;
    private javax.swing.JLabel lblPrecioSug03;
    private javax.swing.JLabel lblPrecioSug04;
    private javax.swing.JLabel lblProductSug01;
    private javax.swing.JLabel lblProductSug02;
    private javax.swing.JLabel lblProductSug03;
    private javax.swing.JLabel lblProductSug04;
    private javax.swing.JLabel lblSetlist;
    private javax.swing.JLabel lblUnidad;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado1;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado2;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado3;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado4;
    private javax.swing.JPanel pnlBase;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlDatosProducto;
    private javax.swing.JPanel pnlFondo;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgSug01;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgSug02;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgSug03;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgSug04;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlMas;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlMenos;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlSugerencia01;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlSugerencia02;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlSugerencia03;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlSugerencia04;
    // End of variables declaration//GEN-END:variables
}
