
package itson.org.ghosttracks.presentacion.cliente.metodosDePago;

/**
 *
 * @author oliro
 */
public class PanelMetodoPagoTarjetaDebito extends javax.swing.JPanel {
    
    public PanelMetodoPagoTarjetaDebito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        panelRedondeado = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblMetodoDePago = new javax.swing.JLabel();
        lblSeleccionMetodoPago = new javax.swing.JLabel();
        txtNumeroTarjeta = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNumeroSeguridad = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtFechaVencimiento = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNombreTitular = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnContinuar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnVolver = new javax.swing.JButton();

        setOpaque(false);

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));

        panelRedondeado.setBackground(new java.awt.Color(217, 217, 217));
        panelRedondeado.setPreferredSize(new java.awt.Dimension(700, 335));

        lblMetodoDePago.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblMetodoDePago.setText("Tarjeta de Débito");

        lblSeleccionMetodoPago.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblSeleccionMetodoPago.setText("Método de Pago");

        txtNumeroTarjeta.setText("Número de tarjeta");
        txtNumeroTarjeta.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        txtNumeroSeguridad.setText("CVV");
        txtNumeroSeguridad.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtNumeroSeguridad.setName("CVV"); // NOI18N
        txtNumeroSeguridad.addActionListener(this::txtNumeroSeguridadActionPerformed);

        txtFechaVencimiento.setText("Fecha Vencimiento");
        txtFechaVencimiento.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        txtNombreTitular.setText("Nombre del titular");
        txtNombreTitular.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        btnContinuar.setBackground(new java.awt.Color(230, 94, 7));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnContinuar.setHoverColor(new java.awt.Color(255, 255, 255));

        btnVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);

        javax.swing.GroupLayout panelRedondeadoLayout = new javax.swing.GroupLayout(panelRedondeado);
        panelRedondeado.setLayout(panelRedondeadoLayout);
        panelRedondeadoLayout.setHorizontalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelRedondeadoLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMetodoDePago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRedondeadoLayout.createSequentialGroup()
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addComponent(txtNombreTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lblSeleccionMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );
        panelRedondeadoLayout.setVerticalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMetodoDePago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblSeleccionMetodoPago)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSeguridadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMetodoDePago;
    private javax.swing.JLabel lblSeleccionMetodoPago;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtFechaVencimiento;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNombreTitular;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroSeguridad;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
