
package itson.org.ghosttracks.presentacion.cliente.metodosDePago;

/**
 *
 * @author nafbr
 */
public class PantallaMetodoPagoTarjetaDeb extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaMetodoPagoTarjetaDeb.class.getName());

    /**
     * Creates new form PantallaMetodoPagoTarjetaDeb
     */
    public PantallaMetodoPagoTarjetaDeb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlBarraSuperiorCorta = new itson.org.ghosttracks.utilerias.pnlBarraSuperiorCorta();
        panelRedondeado = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblMetodoDePago = new javax.swing.JLabel();
        lblSeleccionMetodoPago = new javax.swing.JLabel();
        txtNumeroTarjeta = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNumeroSeguridad = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtFechaVencimiento = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        txtNombreTitular = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnContinuar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        pnlResumenPedido1 = new itson.org.ghosttracks.utilerias.pnlResumenPedido();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));

        panelRedondeado.setBackground(new java.awt.Color(217, 217, 217));

        lblMetodoDePago.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblMetodoDePago.setText("Tarjeta de Débito");

        lblSeleccionMetodoPago.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblSeleccionMetodoPago.setText("Método de Pago");

        txtNumeroTarjeta.setText("Número de tarjeta");
        txtNumeroTarjeta.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        txtNumeroSeguridad.setText("CVV");
        txtNumeroSeguridad.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        txtNumeroSeguridad.setName("CVV"); // NOI18N
        txtNumeroSeguridad.addActionListener(this::txtNumeroSeguridadActionPerformed);

        txtFechaVencimiento.setText("Fecha Vencimiento");
        txtFechaVencimiento.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        txtNombreTitular.setText("Nombre del titular");
        txtNombreTitular.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N

        btnContinuar.setBackground(new java.awt.Color(230, 94, 7));
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnContinuar.setHoverColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRedondeadoLayout = new javax.swing.GroupLayout(panelRedondeado);
        panelRedondeado.setLayout(panelRedondeadoLayout);
        panelRedondeadoLayout.setHorizontalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRedondeadoLayout.createSequentialGroup()
                        .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addComponent(txtNombreTitular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lblSeleccionMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );
        panelRedondeadoLayout.setVerticalGroup(
            panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeadoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblMetodoDePago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(txtNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(panelRedondeadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeadoLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblSeleccionMetodoPago)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(pnlBarraSuperiorCorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlResumenPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBarraSuperiorCorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResumenPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRedondeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(226, 226, 226))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSeguridadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnContinuar;
    private javax.swing.JLabel lblMetodoDePago;
    private javax.swing.JLabel lblSeleccionMetodoPago;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado;
    private itson.org.ghosttracks.utilerias.pnlBarraSuperiorCorta pnlBarraSuperiorCorta;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.pnlResumenPedido pnlResumenPedido1;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtFechaVencimiento;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNombreTitular;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroSeguridad;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
